### ISSUE TITLE
_colors.css Would not affect the role colors within index.html

### ISSUE THREAD

**Issue by DEV-DIBSTER** [Domin-MND/profile-card#2]
According to the CSS [readme.md](https://github.com/Domin-MND/profile-card/blob/main/public/styles/README.md), it says to edit _colors.scss to edit the role colors. 

But this wouldn't affect it as the role colors are being taken from main.css [here](https://github.com/Domin-MND/profile-card/blob/main/public/styles/main.css#L387).

**Comment by dominnya** [comment]
https://github.com/Domin-MND/profile-card/blob/24a22a730d31c86563bc7881bdb3ee066fd72c7d/public/styles/README.md?plain=1#L3-L4

When you're editing .scss/.sass files they're not rendered in the client side, `main.css` is a precompiled CSS file used. Consider using any compiling VS code/Webstorm extensions for SASS if you're editing these files, else edit `main.css` instead.
